@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 服务端: Authentication Request
服务端 --> 客户端: Authentication Response
客户端 -> 服务端: Authentication Request
服务端 --> 客户端: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

@enduml