spring:
  application:
    name: consul-fb-consumerdemo2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        heartbeat:
          enabled: true